name: "sr_vggf2"
phase: "train"
gpu_ids:
  - 6
  - 4
  - 2
  - 0
path:
  pretrained_modelpath: ""
  log: "logs"
  tb_logger: "tb_logger"
  results: "results"
  checkpoint: "checkpoint"
  resume_state: null
datasets:
  train:
    name: "VGGF2_Train"
    mode: "HR"
    dataroot: "contents/vgg_face2_train_32_128"
    datatype: "img"
    l_resolution: 32
    r_resolution: 128
    batch_size: 4
    num_workers: 8
    use_shuffle: true
    data_len: 10000
  val:
    name: "VGGF2_eval"
    mode: "LRHR"
    dataroot: "contents/vgg_face2_eval_32_128"
    datatype: "img"
    l_resolution: 32
    r_resolution: 128
    data_len: 50
model:
  which_model_G: "sr3"
  finetune_norm: false
  unet:
    in_channel: 6
    out_channel: 3
    inner_channel: 64
    channel_multiplier:
      - 1
      - 2
      - 4
      - 8
      - 8
    attn_res:
      - 16
    res_blocks: 2
    dropout: 0.2
  beta_schedule:
    train:
      schedule: "linear"
      n_timestep: 2000
      linear_start: 0.000001
      linear_end: 0.01
    val:
      schedule: "linear"
      n_timestep: 2000
      linear_start: 0.000001
      linear_end: 0.01
  diffusion:
    image_size: 128
    channels: 3
    conditional: true
train:
  n_iter: 1000000
  val_freq: 10000
  save_checkpoint_freq: 10000
  print_freq: 200
  optimizer:
    type: "adam"
    lr: 0.0001
  ema_scheduler:
    step_start_ema: 5000
    update_ema_every: 1
    ema_decay: 0.9999
wandb:
  project: "sr_vggf2"


# python main.py -p train -c config/sr_sr3_VGGF2_32_128.yml
